apiVersion: v1
kind: Service
metadata:
  name: mailpiece-processor-service
  labels:
    app: mailpiece-processor
spec:
  clusterIP: None
  selector:
    app: mailpiece-processor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mailpiece-processor
spec:
  serviceName: mailpiece-processor
  selector:
      matchLabels:
        app: mailpiece-processor
  replicas: 2
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: mailpiece-processor
    spec:
      restartPolicy: Always
      containers:
        - name: mailpiece-processor
          image: mailpiece-processor:0.1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mailpiece-processor-state-store
              mountPath: /data/kafka-streams
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_PROFILES_ACTIVE
              value: "k8"
          ports:
            - containerPort: 7070
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 100
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
  volumeClaimTemplates:
  - metadata:
      name: mailpiece-processor-state-store
    spec:
      volumeMode: Filesystem
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
---
kind: Service
apiVersion: v1
metadata:
  name: mailpiece-processor
spec:
  selector:
    app: mailpiece-processor
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
