apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: logistics.mailpiece-state-elasticsearch-sink
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  tasksMax: 1
  config:
    connection.url: http://elasticsearch.mailpiece.svc:9200
    topics: logistics.Mailpiece-state
    type.name: _doc
    key.ignore: false
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    schema.ignore: true