server:
  port: 9090
  http2:
    enabled: true

ksqldb:
  url: http://localhost:8088

logging:
  level:
    root: WARN
    ch.post: DEBUG
    org.apache.kafka: WARN
    reactor.netty.http.client: DEBUG

management:
  endpoint.health:
    show-details: always
    show-components: always
    probes.enabled: true
  security.enabled: false
  endpoints.web.exposure.include: '*'
  metrics:
    enable:
      jvm: false

spring:
  application:
    name: mailpiece-processor
