apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  annotations:
    strimzi.io/use-connector-resources: "true"  
spec:
  version: 3.2.0
  replicas: 1
  bootstrapServers: kafka-kafka-bootstrap.mailpiece.svc:9092
  build:
    output:
      type: docker
      image: docker.io/chiodoni/kafka-connect:latest
      pushSecret: docker-registry-credentials
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.9.3.Final/debezium-connector-postgres-1.9.3.Final-plugin.tar.gz
      - name: kafka-connect-elasticsearch
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-elasticsearch/versions/13.0.0/confluentinc-kafka-connect-elasticsearch-13.0.0.zip
      - name: kafka-connect-jdbc
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-jdbc/versions/10.5.0/confluentinc-kafka-connect-jdbc-10.5.0.zip
      - name: kafka-connect-datagen
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-datagen/versions/0.5.3/confluentinc-kafka-connect-datagen-0.5.3.zip
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
